### PR TITLE
delete unused tests

### PR DESCRIPTION
**Pull request by rickystewart**
Delete all the tests that we don't use in the cockroach sqlite logic tests.
This makes the archive ~650MB smaller.

### CODE REVIEW

**Comment by rytaft** [comment]
I wasn't aware that we weren't running all these tests -- but now that I am I'd much rather put some effort into trying to actually run them than just deleting them all. Unfortunately I don't think I can tell you right now which tests we might run someday and which ones we won't. Is it critical to reduce the size of the archive right now?

**Comment by rytaft** [comment]
Here is a comment from `logic.go` that explains why we don't currently run some of them:
```
		// TODO(pmattis): Incompatibilities in numeric types.
		// For instance, we type SUM(int) as a decimal since all of our ints are
		// int64.
		// "/test/random/expr/*.test",

		// TODO(pmattis): We don't support unary + on strings.
		// "/test/index/random/*/*.test",
		// "/test/random/aggregates/*.test",
		// "/test/random/groupby/*.test",
		// "/test/random/select/*.test",
```
Seems like we should try to fix these incompatibilities if at all possible so we can start running them.

**Comment by rickystewart** [comment]
> Is it critical to reduce the size of the archive right now?

No -- the motivation is that since we're moving to generating test code for the logic tests, that means that anyone who wants to do that code generation (most CRDB developers, probably) will have to download this archive. This archive is huge (about a gig) and given that we never use 2/3rds of the files in the archive, making people do that entire download/store all this stuff on their machines regardless of whether they actually ever run these tests seemed wasteful.

If the feeling is that we are going to work to increase coverage then I don't have to make this change.

**Comment by rytaft** [comment]
I opened https://github.com/cockroachdb/cockroach/issues/84513 to cover the work to actually run these tests. In the process of addressing that issue we may decide that some of these tests should never be run -- in which case we can revisit this PR and delete those tests.

**Pull request closed without merging**
